/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const VerifyLazyRouteImport = createFileRoute('/verify')()
const ProveLazyRouteImport = createFileRoute('/prove')()
const IndexLazyRouteImport = createFileRoute('/')()

const VerifyLazyRoute = VerifyLazyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/verify.lazy').then((d) => d.Route))
const ProveLazyRoute = ProveLazyRouteImport.update({
  id: '/prove',
  path: '/prove',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/prove.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/prove': typeof ProveLazyRoute
  '/verify': typeof VerifyLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/prove': typeof ProveLazyRoute
  '/verify': typeof VerifyLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/prove': typeof ProveLazyRoute
  '/verify': typeof VerifyLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prove' | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prove' | '/verify'
  id: '__root__' | '/' | '/prove' | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProveLazyRoute: typeof ProveLazyRoute
  VerifyLazyRoute: typeof VerifyLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prove': {
      id: '/prove'
      path: '/prove'
      fullPath: '/prove'
      preLoaderRoute: typeof ProveLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProveLazyRoute: ProveLazyRoute,
  VerifyLazyRoute: VerifyLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
