name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: noir-lang/noirup@v0.1.4
      - uses: oven-sh/setup-bun@v2

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            build-circuit-types = { dir = "circuit", run = "tsc -p tsconfig.build.json" }
            build-circuit-dist = { dir = "circuit", run = "bun build.ts" }
            build-circuit = { dir = "circuit", run = ["nargo compile", "mise r build-circuit-*", "cp dist/worker.js target/circuit.json ../node_modules/@noir-lang/acvm_js/web/acvm_js_bg.wasm ../node_modules/@noir-lang/noirc_abi/web/noirc_abi_wasm_bg.wasm ../web/public/"] }
            build-web = { dir = "web", run = ["tsc -b", "bun vite build"] }
            build = { run = ["mise r build-circuit", "mise r build-web"] }
            [tools]
            "npm:typescript" = "latest"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: mise r build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./web/dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
