name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - name: Install Noir toolchain
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
          echo "$HOME/.nargo/bin" >> $GITHUB_PATH
          ~/.nargo/bin/noirup
      - name: Build
        env:
          CI: true
        run: |
          mise run build
          # GitHub Pages SPA routing workaround
          # GitHub Pages doesn't natively support client-side routing for SPAs.
          # When accessing routes like /prove directly, GitHub looks for prove.html (which doesn't exist).
          # By copying index.html to 404.html, GitHub serves our app on any "not found" route,
          # allowing TanStack Router to handle the routing client-side.
          # Ref: https://github.com/rafgraph/spa-github-pages
          # GitHub Docs: https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site
          cp ./web/dist/index.html ./web/dist/404.html
      - uses: actions/configure-pages@v4
        with:
          enablement: true
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./web/dist"
      - uses: actions/deploy-pages@v4
        id: deployment
